FROM alpine:latest
MAINTAINER minhpq331@gmail.com

WORKDIR /app/bin

ONBUILD COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

ONBUILD COPY --from=builder /app/dist/server /app/bin/server

CMD ["/app/bin/server"]
